### ISSUE TITLE
make new branch for deployable heroku version

### ISSUE THREAD

**Issue by herokuhint** [mahyarkermani/Download-posts-from-Telegram-and-upload-on-Instagram#1]
Hi mahyar , 

1 - please make changes on your python code to deployable on heroku , with free account on heroku , u can deploy your code into upto 5 free dyno without credit card needed . your python code now read gecko path from local . you must be change it using documents tell in buildpack below 👇:

https://elements.heroku.com/buildpacks/pyronlaboratory/heroku-integrated-firefox-geckodriver

2 - your code always ask telegram session fields & must be change to if session file exist in plugin folder , read it from there .

waiting for your changes commits :)
finest regards

**Comment by mahyarkermani** [comment]
Hi, I read your plans and ideas. In the next updates of the program, I will definitely add this feature to it.
